# https://taskfile.dev

version: '3'

env:
  # App
  SERVICE_NAME: sguardian
  MODE: Development
  # Database
  DATABASE_DRIVER: pgx
  DATABASE_URL: postgresql://postgres:123456@192.168.100.47/pollos_hermanos
  DATABASE_MAX_OPEN_CONNECTIONS: 25
  DATABASE_MAX_IDDLE_CONNECTIONS: 25
  DATABASE_MAX_IDDLE_TIME: 15m
  # HTTP
  HTTP_SERVER_IDLE_TIMEOUT: 60s
  PORT: 8080
  HTTP_SERVER_READ_TIMEOUT: 1s
  HTTP_SERVER_WRITE_TIMEOUT: 2s
  #JWT
  TOKEN_TTL: 3600
  JWT_PRIVATE_KEY: FLDSMDFR
  # Email
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: 2525
  MAIL_USERNAME:
  MAIL_PASSWORD:
  MAIL_ENCRYPTION: tls

tasks:
  build:
    cmds:
      - env CGO_ENABLED=0 GOOS=linux go build -ldflags '-w -s' -a -installsuffix cgo -o bin/$SERVICE_NAME ./src/cmd/app/main.go

  test:
    desc: Run all tests ignoring cache
    cmds:
      - go test -cover -v ./... -count=1


  run_local:
    cmds:
      - ./bin/$SERVICE_NAME

  clean:
    cmds:
      - rm -fr ./bin

  db_up:
    cmds:
      - migrate -path=./migrations -database=$(DATABASE_URL) up

  db_down:
    cmds:
      - migrate -path=./migrations -database=$(DATABASE_URL) down